const { Router } = require('express')
const rateLimit = require('express-rate-limit')
const authHandler = require('./handlers/auth/index')
const randomFacts = require('./controllers/facts/randomFacts')
const getAllTags = require('./controllers/utils/listTags')
const getOwoify = require('./controllers/utils/owoify')
const getUwuify = require('./controllers/utils/uwuify')
const getUvuify = require('./controllers/utils/uvuify')
const randomWaifus = require('./controllers/waifus/randomWaifus')
const randomPasswords = require('./controllers/utils/randomPassword')
const randomQuotes = require('./controllers/quotes/randomQuotes')
const randomKick = require('./controllers/gifs/randomKick')
const randomKill = require('./controllers/gifs/randomKill')
const randomKissu = require('./controllers/gifs/randomKissu')
const randomMidfing = require('./controllers/gifs/randomMidfing')
const randomNuzzle = require('./controllers/gifs/randomNuzzle')
const randomPunch = require('./controllers/gifs/randomPunch')
const randomShoot = require('./controllers/gifs/randomShoot')
const randomSip = require('./controllers/gifs/randomSip')
const randomSleepy = require('./controllers/gifs/randomSleepy')
const randomSmile = require('./controllers/gifs/randomSmile')
const randomStab = require('./controllers/gifs/randomStab')
const randomStare = require('./controllers/gifs/randomStare')
const randomSuicide = require('./controllers/gifs/randomSuicide')
const randomTease = require('./controllers/gifs/randomTease')
const randomWag = require('./controllers/gifs/randomWag')
const randomBite = require('./controllers/gifs/randomBite')
const randomBlush = require('./controllers/gifs/randomBlush')
const randomBonk = require('./controllers/gifs/randomBonk')
const randomBored = require('./controllers/gifs/randomBored')
const randomBully = require('./controllers/gifs/randomBully')
const randomBye = require('./controllers/gifs/randomBye')
const randomChase = require('./controllers/gifs/randomChase')
const randomCheer = require('./controllers/gifs/randomCheer')
const randomDab = require('./controllers/gifs/randomDab')
const randomDie = require('./controllers/gifs/randomDie')
const randomDisgust = require('./controllers/gifs/randomDisgust')
const randomFeed = require('./controllers/gifs/randomFeed')
const randomHi = require('./controllers/gifs/randomHi')
const randomHold = require('./controllers/gifs/randomHold')
const randomHug = require('./controllers/gifs/randomHug')
const randomNope = require('./controllers/gifs/randomNope')
const randomPanic = require('./controllers/gifs/randomPanic')
const randomPat = require('./controllers/gifs/randomPat')
const randomPeck = require('./controllers/gifs/randomPeck')
const randomPoke = require('./controllers/gifs/randomPoke')
const randomPout = require('./controllers/gifs/randomPout')
const randomRun = require('./controllers/gifs/randomRun')
const randomSad = require('./controllers/gifs/randomSad')
const randomShrug = require('./controllers/gifs/randomShrug')
const randomSlap = require('./controllers/gifs/randomSlap')
const randomSmug = require('./controllers/gifs/randomSmug')
const randomThink = require('./controllers/gifs/randomThink')
const randomThumbsup = require('./controllers/gifs/randomThumbsup')
const randomTickle = require('./controllers/gifs/randomTickle')
const randomTriggered = require('./controllers/gifs/randomTriggered')
const randomWave = require('./controllers/gifs/randomWave')
const randomWink = require('./controllers/gifs/randomWink')
const randomYes = require('./controllers/gifs/randomYes')
const randomAngry = require('./controllers/gifs/randomAngry')
const randomCringe = require('./controllers/gifs/randomCringe')
const randomCry = require('./controllers/gifs/randomCry')
const randomCuddle = require('./controllers/gifs/randomCuddle')
const randomDance = require('./controllers/gifs/randomDance')
const randomFacepalm = require('./controllers/gifs/randomFacepalm')
const randomGlomp = require('./controllers/gifs/randomGlomp')
const randomHappy = require('./controllers/gifs/randomHappy')
const randomHighfive = require('./controllers/gifs/randomHighfive')
const randomLaugh = require('./controllers/gifs/randomLaugh')
const randomLick = require('./controllers/gifs/randomLick')
const randomLove = require('./controllers/gifs/randomLove')
const randomLurk = require('./controllers/gifs/randomLurk')
const randomNervous = require('./controllers/gifs/randomNervous')
const randomNom = require('./controllers/gifs/randomNom')
const randomBaka = require('./controllers/gifs/randomBaka')
const userEndpoint = require('./controllers/utils/user')

const router = Router()

// Rate Limiter for Fact || Other endpoints
const Limiter = rateLimit({
  windowMs: 1000, // 1 second
  max: 2, // limit each IP to 5 requests per windowMs
  message: {
    status: 429,
    message: 'Too many requests, please try again later.',
  },
})

// Base API
router.get('/api', (req, res) => {
  res.redirect('https://docs.waifu.it/list-of-endpoints')
})

router.all('/api/user', userEndpoint)

// Fact Endpoints
router.get('/api/fact', Limiter, authHandler, randomFacts)

// Waifu Endpoint
router.get('/api/waifu', Limiter, authHandler, randomWaifus)

// Utils Endpoint
router.get('/api/password', Limiter, authHandler, randomPasswords)
router.get('/api/alltags', Limiter, authHandler, getAllTags)
router.get('/api/owoify', Limiter, authHandler, getOwoify)
router.get('/api/uwuify', Limiter, authHandler, getUwuify)
router.get('/api/uvuify', Limiter, authHandler, getUvuify)

// Random Quote Endpoint
router.get('/api/quote', Limiter, authHandler, randomQuotes)

// Random Gifs Endpoints
router.get('/api/kick', Limiter, authHandler, randomKick)
router.get('/api/kill', Limiter, authHandler, randomKill)
router.get('/api/kiss', Limiter, authHandler, randomKissu)
router.get('/api/midfing', Limiter, authHandler, randomMidfing)
router.get('/api/nuzzle', Limiter, authHandler, randomNuzzle)
router.get('/api/punch', Limiter, authHandler, randomPunch)
router.get('/api/shoot', Limiter, authHandler, randomShoot)
router.get('/api/sip', Limiter, authHandler, randomSip)
router.get('/api/sleepy', Limiter, authHandler, randomSleepy)
router.get('/api/smile', Limiter, authHandler, randomSmile)
router.get('/api/stab', Limiter, authHandler, randomStab)
router.get('/api/stare', Limiter, authHandler, randomStare)
router.get('/api/suicide', Limiter, authHandler, randomSuicide)
router.get('/api/tease', Limiter, authHandler, randomTease)
router.get('/api/wag', Limiter, authHandler, randomWag)
router.get('/api/bite', Limiter, authHandler, randomBite)
router.get('/api/blush', Limiter, authHandler, randomBlush)
router.get('/api/bonk', Limiter, authHandler, randomBonk)
router.get('/api/bored', Limiter, authHandler, randomBored)
router.get('/api/bully', Limiter, authHandler, randomBully)
router.get('/api/bye', Limiter, authHandler, randomBye)
router.get('/api/chase', Limiter, authHandler, randomChase)
router.get('/api/cheer', Limiter, authHandler, randomCheer)
router.get('/api/dab', Limiter, authHandler, randomDab)
router.get('/api/die', Limiter, authHandler, randomDie)
router.get('/api/disgust', Limiter, authHandler, randomDisgust)
router.get('/api/feed', Limiter, authHandler, randomFeed)
router.get('/api/hi', Limiter, authHandler, randomHi)
router.get('/api/hold', Limiter, authHandler, randomHold)
router.get('/api/hug', Limiter, authHandler, randomHug)
router.get('/api/Nope', Limiter, authHandler, randomNope)
router.get('/api/panic', Limiter, authHandler, randomPanic)
router.get('/api/pat', Limiter, authHandler, randomPat)
router.get('/api/peck', Limiter, authHandler, randomPeck)
router.get('/api/poke', Limiter, authHandler, randomPoke)
router.get('/api/punch', Limiter, authHandler, randomPunch)
router.get('/api/pout', Limiter, authHandler, randomPout)
router.get('/api/run', Limiter, authHandler, randomRun)
router.get('/api/sad', Limiter, authHandler, randomSad)
router.get('/api/shrug', Limiter, authHandler, randomShrug)
router.get('/api/slap', Limiter, authHandler, randomSlap)
router.get('/api/smug', Limiter, authHandler, randomSmug)
router.get('/api/think', Limiter, authHandler, randomThink)
router.get('/api/thumbsup', Limiter, authHandler, randomThumbsup)
router.get('/api/tickle', Limiter, authHandler, randomTickle)
router.get('/api/triggered', Limiter, authHandler, randomTriggered)
router.get('/api/wave', Limiter, authHandler, randomWave)
router.get('/api/wink', Limiter, authHandler, randomWink)
router.get('/api/yes', Limiter, authHandler, randomYes)
router.get('/api/angry', Limiter, authHandler, randomAngry)
router.get('/api/cringe', Limiter, authHandler, randomCringe)
router.get('/api/cry', Limiter, authHandler, randomCry)
router.get('/api/cuddle', Limiter, authHandler, randomCuddle)
router.get('/api/dance', Limiter, authHandler, randomDance)
router.get('/api/facepalm', Limiter, authHandler, randomFacepalm)
router.get('/api/glomp', Limiter, authHandler, randomGlomp)
router.get('/api/happy', Limiter, authHandler, randomHappy)
router.get('/api/highfive', Limiter, authHandler, randomHighfive)
router.get('/api/hug', Limiter, authHandler, randomHug)
router.get('/api/laugh', Limiter, authHandler, randomLaugh)
router.get('/api/lick', Limiter, authHandler, randomLick)
router.get('/api/love', Limiter, authHandler, randomLove)
router.get('/api/lurk', Limiter, authHandler, randomLurk)
router.get('/api/nervous', Limiter, authHandler, randomNervous)
router.get('/api/nom', Limiter, authHandler, randomNom)
router.get('/api/baka', Limiter, authHandler, randomBaka)

module.exports = router
